### ISSUE TITLE
Timelock is hard coded

### ISSUE THREAD

**Issue by lerennardleonard** [leon-do/Bitcoin-HTLC-Wallet#1]
Hi,
I think the timelock input actually does nothing since the time is hard coded in the script creation.
`.add(bitcore.crypto.BN.fromNumber(1513412288).toScriptNumBuffer())`

Should'nt it be : 
`.add(bitcore.crypto.BN.fromNumber(timeLock).toScriptNumBuffer())`
Since you got timelock from the DOM ?

**Comment by lerennardleonard** [comment]
I've performed some test and awkwardly, when I put a timelock such as `Date.now()` the redeem txn wont pass and I get `non-mandatory-script-verify-flag (unknown error) (code -26)` 

But if I put a unix timestamp far in the past such as the one you hard coded, then the redeem and the spend transactions are working as expected.

**Comment by leon-do** [comment]
Good catch and you're correct about the time. 

I seem to be stuck on the same issue. There seems to be a discrepancy between the time on chain and the time from the DOM. 

I haven't figured it out yet but if you do, please share your insight

**Comment by lerennardleonard** [comment]
I'm on it, i'll make a pull request if find the problem.

**Comment by lerennardleonard** [comment]
This bug is quite strange, by testing time-locks from the oldest to the newest, I found that the redeem transaction works, if the timelock specified is before April 25 (so about 16 days ago). That's about 1,3M seconds. I don't understand why but I'll investigate it further asap

**Comment by lerennardleonard** [comment]
Ok so I figured it out. The UNIX timestamp on the create script is misleading because the javascript native Date.now() produce an integer counting the number of miliseconds since 1/1/1970 while bitcoin OP_CHECKLOCKTIMEVERIFY expect an integer counting in seconds. I guess you had this figured out too since on your redeem script you do the following : ` .lockUntilDate(Math.floor(Date.now() / 1001)); `
Still I suggest making a relative time instead : 
```
var script = bitcore
            .Script()
            .add('OP_IF')
            .add('OP_SHA256')
            .add(new Buffer(hashKey.toString(), 'hex'))
            .add('OP_EQUALVERIFY')
            .add(bitcore.Script.buildPublicKeyHashOut(bitcore.Address.fromString(toAddress)))
            .add('OP_ELSE')
            .add(bitcore.crypto.BN.fromNumber(Math.floor(Date.now()/1001)+timelock).toScriptNumBuffer())
            .add('OP_CHECKLOCKTIMEVERIFY')
            .add('OP_DROP')
            .add(bitcore.Script.buildPublicKeyHashOut(bitcore.Address.fromString(fromAddress)))
            .add('OP_ENDIF')
        console.log('script.toString() =', script.toString())
```

Do you agree ?

**Comment by leon-do** [comment]
You're correct. It's in seconds. 

We're you able to spend the BTC immediately if the date is Date.now()/1001?

**Comment by lerennardleonard** [comment]
Indeed I was able to spend them with the redeem script. Here are the transactions : 
Create : bbc474297a02a4e38c03246a937e81975f8c5a032019460678bb585fc85a7272
Redeem : 4cdfb3ac6c810a7f2d88304460778072c5ab4476604cb130b316d2737bfdc4ab
(on the testnet)

I've another question, in the event of a cross chain atomic swap, how would you extract the secret key for the transaction ?
I'll explain myself, your createTransaction script creates a spendable output looked with a provided key. I figured out that you would provide the hash of this key to the other party for him to setup a similar contract on the other chain. If the contract is first set up on the other chain we would only have to modify a bit the create script by not hashing the key and providing directly the hashed key. 
But if the scenario is the other way around, how the other participant can extract the key from the transaction ?

**Comment by leon-do** [comment]
you'd have to parse out the transaction.

On the ETH side, you can make the key a public variable.
